### PR TITLE
Added basic documentation

### PR DESCRIPTION
**Pull request by martinheidegger**
This PR contributes a very basic set of documentation, including the license, for users to find its way around.

### CODE REVIEW

**Comment by arvinxx** [comment]
Thanks a lot. Can you get typings after `npm i`?

It seems need to do something to make it valid.

**Comment by martinheidegger** [comment]
At the moment not, I am debugging it right now. _(And I am planning to send a PR once i figured that out)_

**Comment by arvinxx** [comment]
this typings need to be added to tsconfig.json, when it is installed, ts will ignore it cause of it's in node_modules. The easiest way is to add this to the @types repository.But that's too large.

**Comment by martinheidegger** [comment]
It seems there _should_ be a different way to get it running. I am trying out things.

**Comment by arvinxx** [comment]
Maybe you can change the pubilcAPI to index.d.ts and then change the `typings` in `package.json` to `typings/index.d.ts`

I'm outside so can't try now.

**Pull request merged**
